name: cd

on:
  push:
    branches:
      - main
jobs:
  cd:
    name: cd
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Container registry に認証する
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Docker ビルドを実行する
        run: docker build -t ghcr.io/${{ github.repository }}:latest .
      - name: Docker イメージをプッシュする
        run: docker push ghcr.io/${{ github.repository }}:latest
      - name: OIDC 連携により AWS の認証情報を取得する
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}